---
title: "2016 Fall Final Projects"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(knitr)
```


## GitHub Documents

```{r, echo=FALSE}
titles <- c(
  "Where Should MiddKids Ski This J-Term?",
  "Drug Use Within Age Groups",
  "Quantifying Middlebury's Collective Consciousness",
  "Who Sits at the Top of NESCAC Stack? (interactive; takes 30 seconds to load)",
  "Sexism on the Silver Screen: Exploring Film's Gender Divide",
  "Marijuana Retail and Production Dispersal in Colorado",
  "Unemployment and Migration in the United States",
  "Will Your Major Field Change Your Prospects for Employment?",
  "Looking for Mental Health Care? West is Best",
  "The Systematic Gender Gap in STEM Fields: Why Should We Care?"
  )
folder <- c("`skiing`", "`drug_use`", "`middlebury_campus`", "`NESCAC`",
            "`movies`", "`marijuana`", "`unemployment`", "`college_majors`",
            "`mental_health`", "`gender_STEM`")

final_projects <- 
  read_csv("groups.csv") %>%
  mutate(
    Title = titles,
    Folder = folder,
    Title = paste("<a target=\"_blank\" class=\"page-link\" href=\"",  `RPubs Link (Public)`, "\">", Title, "</a>", sep="")
    ) %>% 
  select(-c(`RPubs Link (Public)`))

kable(final_projects)
# write_csv(final_projects, "2016-09_final_projects.csv")
```
