
---
title: "Problem Set 09"
author: "WRITE YOUR NAME HERE"
date: "Due Friday, November 18, 2016"
output:
  html_document
---



## Please Indicate

* Who you collaborated with. If no one, please indicate so: 
* Approximately how much time did you spend on this problem set: 
* What, if anything, gave you the most trouble: 



## Instructions/Hint:

* 

```{r, message=FALSE, echo=FALSE}
library(ggplot2)
library(dplyr)
library(mosaic)
library(readr)
library(knitr)
library(tidyr)
```



## Question 1:

```{r}
grades <- read_csv("grades.csv")

ggplot(data=grades, aes(x=even, y=final)) +
  geom_boxplot()


grades %>% 
  group_by(even) %>% 
  summarise(mean=mean(final))
mean(final ~ even, data=grades)


set.seed(76)
grades %>% 
  mutate(even=shuffle(even)) %>%   
  group_by(even) %>% 
  summarise(mean=mean(final))

set.seed(76)
mean(final ~ shuffle(even), data=grades)
mean(final ~ shuffle(even), data=grades) %>% diff()
observed_diff <- mean(final ~ shuffle(even), data=grades) %>% diff()


simulations <- do(10000) * mean(final ~ shuffle(even), data=grades)
simulations <- simulations %>% 
  mutate(diff=even-odd)

ggplot(data=simulations , aes(x=diff)) +
  geom_histogram() +
  geom_vline(xintercept = observed_diff, col="red")


# This sucks:
simulations <- do(10) * (
  grades %>% 
  mutate(even=shuffle(even)) %>% 
  group_by(even) %>% 
  summarise(mean=mean(final)) %>% 
  tidyr::spread(even, mean)
)
simulations <- simulations %>% 
  select(even, odd)
simulations







```

