---
title: "Future Directions"
author: "Albert Y. Kim"
date: "11/21/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Future Directions



#### Mathematics

1. **MATH 216 Data Science**: This class goes much more in depth with data visualization and manipulation and we work
with much more complex data sets: time series, text data, maps. [`go/MATH216/`](https://rudeboybert.github.io/MATH216/). Prereq: MATH 116
1. **MATH 218 Statistical Learning**: Building off MATH 116, this is a machine learning class. 
Can we teach a computer to learn from data. One example of machine learning: netflix recommendations. Based on what you've seen and your
ratings, can you teach a computer to recommend movies you'll like. Prereq: MATH 116
1. **MATH 310 Probability**: Instead of taking a computational approach to understanding randomness, this class takes a mathematical/analytic
approach. So instead of describing the behavior of coin flips, die rolls, and any other random process via simulations, we use
mathematical formalas. Prereq: MATH 223 Multivariate Calculus
1. **MATH 311 Theory of Statistics**: In MATH 116 we take for granted that a lot of the statistical methods work. In this class, we
unpack and prove why they work. Prereq: MATH 310 Probability


#### Computer Science

1. **CSCI 101 Intro to Computing or CSCI 150 Computing for the Sciences**: If you enjoyed your first foray into
programming and want to learn more, then definitely take this class. The things about learning programming
languages, much like learning verbal languages, after you learn your first new one, all future ones become
easier and easier to learn.
1. **CSCI 465 Information Visualization**: A much more in depth treatment of data Visualization


#### Economics

1. **ECON 211 Regression Analysis**. A much more in depth treatment of regression than in MATH 116
1. **ECON 212 Empirical Economics Research**: Prof Caitlin Myers' class on econometrics and establishing **causality**: when does X cause Y?


#### Others
